

FROM ubuntu

RUN apt-get update
RUN apt-get -y install apt-utils
RUN apt-get -y install apache2
RUN apt-get -y install vim
RUN apt-get -y install sed
RUN apt-get -y install ufw
RUN apt-get -y install curl
RUN apt-get -y install iputils-ping
#Owncloud listens on port 80
EXPOSE 80
RUN mkdir setup
ADD setup.sh /setup
