

FROM ubuntu



RUN apt-get update
RUN apt-get -y install apt-utils
RUN apt-get -y install apache2
RUN apt-get -y install vim
RUN apt-get -y install sed
RUN apt-get -y install ufw
RUN apt-get -y install curl
RUN apt-get -y install iputils-ping
#Install MySql server
RUN export DEBIAN_FRONTEND=noninteractive
RUN echo "mysql-server-5.6 mysql-server/root_password password root" |  debconf-set-selections
RUN echo "mysql-server-5.6 mysql-server/root_password_again password root" |  debconf-set-selections
RUN apt-get -y install mysql-server
#Owncloud listens on port 120
EXPOSE 80
RUN mkdir setup
ADD setup.sh /setup
