

FROM ubuntu

RUN apt-get update
RUN apt-get -y install apache2
RUN apt-get -y install vim
RUN apt-get -y install ufw
RUN apt-get -y install iputils-ping 
RUN mkdir installation
ADD installation.sh /installation
