FROM ubuntu

RUN apt-get update &&  apt-get -y upgrade
RUN apt-get -y install sudo
RUN apt-get -y install wget
RUN apt-get -y install wget python-minimal
RUN cd && wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
#CMD python install.py --production --user frappe
EXPOSE 80
